Repository intel/intel-device-plugins-for-kubernetes, pull requests merged in 2020-09, with the labels that each got.

#460 sync README.md files with the current state of the code
  DEVEL.md
  README.md
  cmd/fpga_crihook/README.md
  cmd/fpga_plugin/README.md
  cmd/fpga_tool/README.md
  cmd/gpu_plugin/README.md
  cmd/qat_plugin/README.md
  cmd/sgx_plugin/README.md
Labels: docs

#459 FPGA: upgrade OPAE to v.1.5.0-2
  demo/opae-nlb-demo/0001-OPAE-in-containers-don-t-enumerate-missing-device.patch
  demo/opae-nlb-demo/Dockerfile
Labels: fpga

#463 sgx-sdk-demo: update build
  demo/sgx-sdk-demo/Dockerfile
Labels: sgx

#454 Documentation: Fixes broken links and standardizes headers.
  DEVEL.md
  README.md
  cmd/fpga_admissionwebhook/README.md
  cmd/fpga_crihook/README.md
  cmd/fpga_plugin/README.md
  cmd/fpga_tool/README.md
  cmd/gpu_plugin/README.md
  cmd/operator/README.md
  cmd/qat_plugin/README.md
  cmd/sgx_plugin/README.md
  cmd/vpu_plugin/README.md
  demo/readme.md
Labels: docs
